name: anned_finds
description: "A Flutter e-commerce application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # Firebase - Latest working versions (as of late 2024)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  
  # Authentication providers
  google_sign_in: ^6.2.1
  
  # State management and utilities
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  
  # Network and data handling
  http: ^1.1.2
  intl: ^0.19.0
  
  # Image handling
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  
  # Utilities
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Remove assets section if folders don't exist
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Remove fonts section if font files don't exist
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700